version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    environment:
      - LMQ_STDOUT_LEVEL: debug
      - LMQ_TEST_PUBLISH_COUNT: 100000
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Running tests
          command: go test -v ./...